name: Android CI

on:
  push:
    branches: 
      - develop
      - release/*
      - master
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - name: Run Tests
      run: ./gradlew test
    - name: Build with Gradle
      run: ./gradlew assemble
