name: Generate Gradle Dependencies

on:
  push:
    branches:
      - develop
jobs:
  generate-dependency-graph:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v3
      - name: Submit Gradle Dependencies
        uses: mikepenz/gradle-dependency-submission@v0.8.6
        with:
          gradle-build-configuration-mapping:
            - :app|releaseCompileClasspath
            - :pat-static|compileClasspath
          sub-module-mode: COMBINED
